export const EVENT = {
  session_started: 'session_started',
  message_received: 'message_received',
  welcome_sent: 'welcome_sent',
  grade_captured: 'grade_captured',
  subject_captured: 'subject_captured',
  board_captured: 'board_captured',
  onboarding_completed: 'onboarding_completed',
  microlesson_sent: 'microlesson_sent',
  topic_rejected: 'topic_rejected',
  topic_provided: 'topic_provided',
  generation_started: 'generation_started',
  generation_succeeded: 'generation_succeeded',
  generation_failed: 'generation_failed',
  worksheet_delivered: 'worksheet_delivered',
  pdf_delivered: 'pdf_delivered',
  pdf_failed: 'pdf_failed',
  reusable_prompt_sent: 'reusable_prompt_sent',
  impact_prompt_sent: 'impact_prompt_sent',
  impact_reported: 'impact_reported',
  referral_reported: 'referral_reported',
  share_cta_sent: 'share_cta_sent',
  activated: 'activated',
  skill_completed: 'skill_completed',
  nudge_scheduled: 'nudge_scheduled',
  nudge_sent: 'nudge_sent',
  nudge_failed: 'nudge_failed',
  nudge_reopened: 'nudge_reopened',
  help_requested: 'help_requested',
  restarted: 'restarted',
  unrecognized_input: 'unrecognized_input',
  still_working_sent: 'still_working_sent',
  error_occurred: 'error_occurred',
  message_status: 'message_status',
} as const;

export type EventName = (typeof EVENT)[keyof typeof EVENT];
