export const EVENT = {
  session_started: 'session_started',
  message_received: 'message_received',
  welcome_sent: 'welcome_sent',
  grade_captured: 'grade_captured',
  subject_captured: 'subject_captured',
  board_captured: 'board_captured',
  onboarding_completed: 'onboarding_completed',
  microlesson_sent: 'microlesson_sent',
  topic_rejected: 'topic_rejected',
  topic_provided: 'topic_provided',
  generation_started: 'generation_started',
  generation_succeeded: 'generation_succeeded',
  generation_failed: 'generation_failed',
  worksheet_delivered: 'worksheet_delivered',
  pdf_delivered: 'pdf_delivered',
  pdf_failed: 'pdf_failed',
  reusable_prompt_sent: 'reusable_prompt_sent',
  impact_prompt_sent: 'impact_prompt_sent',
  impact_reported: 'impact_reported',
  referral_reported: 'referral_reported',
  share_cta_sent: 'share_cta_sent',
  activated: 'activated',
  skill_completed: 'skill_completed',
  nudge_scheduled: 'nudge_scheduled',
  nudge_sent: 'nudge_sent',
  nudge_failed: 'nudge_failed',
  /** A due nudge was postponed because the teacher is mid-conversation. Emitted so a nudge that
   *  does not fire is visible in metrics instead of vanishing, which is how the old silent drop
   *  hid the fact that every nudge in the pilot was being discarded. */
  nudge_deferred: 'nudge_deferred',
  nudge_reopened: 'nudge_reopened',
  help_requested: 'help_requested',
  restarted: 'restarted',
  unrecognized_input: 'unrecognized_input',
  still_working_sent: 'still_working_sent',
  error_occurred: 'error_occurred',
  message_status: 'message_status',
  paper_started: 'paper_started',
  paper_subject_captured: 'paper_subject_captured',
  paper_chapter_captured: 'paper_chapter_captured',
  paper_media_received: 'paper_media_received',
  paper_media_rejected: 'paper_media_rejected',
  paper_media_done: 'paper_media_done',
  paper_type_captured: 'paper_type_captured',
  paper_tiers_captured: 'paper_tiers_captured',
  paper_key_captured: 'paper_key_captured',
  paper_school_captured: 'paper_school_captured',
  paper_logo_captured: 'paper_logo_captured',
  paper_generation_started: 'paper_generation_started',
  paper_qc_completed: 'paper_qc_completed',
  paper_generated: 'paper_generated',
  paper_generation_failed: 'paper_generation_failed',
  paper_preview_sent: 'paper_preview_sent',
  paper_redo_requested: 'paper_redo_requested',
  paper_exported: 'paper_exported',
  paper_minutes_saved: 'paper_minutes_saved',
} as const;

export type EventName = (typeof EVENT)[keyof typeof EVENT];
